cursor #dde4e2
cursor_text_color #bec9c7

foreground            #dde4e2
background            #0e1514
selection_foreground  #1c3533
selection_background  #b0ccc9
url_color             #81d5ce

color0   #0e1514
color1   #f49d6e
color2   #6ad572
color3   #fff472
color4   #6acac2
color5   #1b625c
color6   #81d5ce
color7   #d2dfde
color8   #808a89
color9   #ffc09f
color10  #a5ffac
color11  #fff8a5
color12  #9beae3
color13  #b8fff9
color14  #d1fffb
color15  #f8fffe
