cursor #dde4e1
cursor_text_color #bec9c5

foreground            #dde4e1
background            #0e1513
selection_foreground  #1c3530
selection_background  #b1ccc6
url_color             #83d5c6

color0   #0e1513
color1   #f49b6e
color2   #6ad571
color3   #fff372
color4   #6ccab9
color5   #1c6255
color6   #83d5c6
color7   #d2dfdd
color8   #808a88
color9   #ffbf9f
color10  #a5ffab
color11  #fff7a5
color12  #9deadc
color13  #bafff2
color14  #d2fff6
color15  #f8fffd
