# vim:fileencoding=utf-8:foldmethod=marker

###############################
##        Appearance         ##
###############################
lines 25
columns 80
he number of columns shown in the panel. Ignored for background,
edge top
background_opacity 0.85
hide_on_focus_loss no
grab_keyboard no
margin_left 0
margin_right 0
margin_top 0
margin_bottom 0
kitty_conf
kitty_override
app_id kitty-quick-access
output_name
start_as_hidden no
focus_policy exclusive
