# Salesforce CLI autocomplete for Fish shell
# Auto-generated from 'sf commands' output
# Place in: ~/.config/fish/completions/sf.fish

complete -c sf -f

# Top-level commands
complete -c sf -n '__fish_use_subcommand' -a 'agent'
complete -c sf -n '__fish_use_subcommand' -a 'alias'
complete -c sf -n '__fish_use_subcommand' -a 'analytics'
complete -c sf -n '__fish_use_subcommand' -a 'apex'
complete -c sf -n '__fish_use_subcommand' -a 'api'
complete -c sf -n '__fish_use_subcommand' -a 'autocomplete'
complete -c sf -n '__fish_use_subcommand' -a 'cmdt'
complete -c sf -n '__fish_use_subcommand' -a 'code-analyzer'
complete -c sf -n '__fish_use_subcommand' -a 'commands'
complete -c sf -n '__fish_use_subcommand' -a 'community'
complete -c sf -n '__fish_use_subcommand' -a 'config'
complete -c sf -n '__fish_use_subcommand' -a 'data'
complete -c sf -n '__fish_use_subcommand' -a 'dev'
complete -c sf -n '__fish_use_subcommand' -a 'doctor'
complete -c sf -n '__fish_use_subcommand' -a 'flow'
complete -c sf -n '__fish_use_subcommand' -a 'force'
complete -c sf -n '__fish_use_subcommand' -a 'help'
complete -c sf -n '__fish_use_subcommand' -a 'info'
complete -c sf -n '__fish_use_subcommand' -a 'lightning'
complete -c sf -n '__fish_use_subcommand' -a 'logic'
complete -c sf -n '__fish_use_subcommand' -a 'org'
complete -c sf -n '__fish_use_subcommand' -a 'package'
complete -c sf -n '__fish_use_subcommand' -a 'package1'
complete -c sf -n '__fish_use_subcommand' -a 'plugins'
complete -c sf -n '__fish_use_subcommand' -a 'project'
complete -c sf -n '__fish_use_subcommand' -a 'schema'
complete -c sf -n '__fish_use_subcommand' -a 'search'
complete -c sf -n '__fish_use_subcommand' -a 'sobject'
complete -c sf -n '__fish_use_subcommand' -a 'static-resource'
complete -c sf -n '__fish_use_subcommand' -a 'update'
complete -c sf -n '__fish_use_subcommand' -a 'version'
complete -c sf -n '__fish_use_subcommand' -a 'visualforce'
complete -c sf -n '__fish_use_subcommand' -a 'whatsnew'
complete -c sf -n '__fish_use_subcommand' -a 'which'

# Subcommands
complete -c sf -n "__fish_seen_subcommand_from agent" -a 'activate'
complete -c sf -n "__fish_seen_subcommand_from agent" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from agent" -a 'deactivate'
complete -c sf -n "__fish_seen_subcommand_from agent; and not __fish_seen_subcommand_from agent-spec authoring-bundle template test-spec" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from agent" -a 'preview'
complete -c sf -n "__fish_seen_subcommand_from agent; and not __fish_seen_subcommand_from authoring-bundle" -a 'publish'
complete -c sf -n "__fish_seen_subcommand_from agent; and not __fish_seen_subcommand_from create list results resume run" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from agent; and not __fish_seen_subcommand_from authoring-bundle" -a 'validate'
complete -c sf -n "__fish_seen_subcommand_from alias" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from alias" -a 'set'
complete -c sf -n "__fish_seen_subcommand_from alias" -a 'unset'
complete -c sf -n "__fish_seen_subcommand_from analytics; and not __fish_seen_subcommand_from template" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from apex; and not __fish_seen_subcommand_from class trigger" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from apex; and not __fish_seen_subcommand_from log test" -a 'get'
complete -c sf -n "__fish_seen_subcommand_from apex; and not __fish_seen_subcommand_from log" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from apex; and not __fish_seen_subcommand_from test" -a 'run'
complete -c sf -n "__fish_seen_subcommand_from apex; and not __fish_seen_subcommand_from log" -a 'tail'
complete -c sf -n "__fish_seen_subcommand_from api; and not __fish_seen_subcommand_from graphql rest" -a 'request'
complete -c sf -n "__fish_seen_subcommand_from cmdt; and not __fish_seen_subcommand_from field fromorg object record records" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from code-analyzer" -a 'config'
complete -c sf -n "__fish_seen_subcommand_from code-analyzer" -a 'rules'
complete -c sf -n "__fish_seen_subcommand_from code-analyzer" -a 'run'
complete -c sf -n "__fish_seen_subcommand_from community" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from community; and not __fish_seen_subcommand_from template" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from community" -a 'publish'
complete -c sf -n "__fish_seen_subcommand_from config" -a 'get'
complete -c sf -n "__fish_seen_subcommand_from config" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from config" -a 'set'
complete -c sf -n "__fish_seen_subcommand_from config" -a 'unset'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from results" -a 'bulk'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from file record" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from bulk record resume" -a 'delete'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from bulk resume tree" -a 'export'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from record" -a 'get'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from bulk resume tree" -a 'import'
complete -c sf -n "__fish_seen_subcommand_from data" -a 'query'
complete -c sf -n "__fish_seen_subcommand_from data" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from data" -a 'search'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from bulk record resume" -a 'update'
complete -c sf -n "__fish_seen_subcommand_from data; and not __fish_seen_subcommand_from bulk resume" -a 'upsert'
complete -c sf -n "__fish_seen_subcommand_from dev; and not __fish_seen_subcommand_from messages" -a 'audit'
complete -c sf -n "__fish_seen_subcommand_from dev; and not __fish_seen_subcommand_from messages script" -a 'convert'
complete -c sf -n "__fish_seen_subcommand_from dev; and not __fish_seen_subcommand_from command flag plugin" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from flow; and not __fish_seen_subcommand_from test" -a 'get'
complete -c sf -n "__fish_seen_subcommand_from flow; and not __fish_seen_subcommand_from test" -a 'run'
complete -c sf -n "__fish_seen_subcommand_from force; and not __fish_seen_subcommand_from bulk" -a 'data'
complete -c sf -n "__fish_seen_subcommand_from force; and not __fish_seen_subcommand_from lwc" -a 'lightning'
complete -c sf -n "__fish_seen_subcommand_from force; and not __fish_seen_subcommand_from push-upgrade" -a 'package'
complete -c sf -n "__fish_seen_subcommand_from info; and not __fish_seen_subcommand_from display" -a 'releasenotes'
complete -c sf -n "__fish_seen_subcommand_from lightning; and not __fish_seen_subcommand_from app component event interface test" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from test" -a 'get'
complete -c sf -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from test" -a 'run'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from permset permsetlicense" -a 'assign'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from sandbox scratch shape snapshot user" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from sandbox scratch shape snapshot" -a 'delete'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from tracking" -a 'disable'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from user" -a 'display'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from tracking" -a 'enable'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from password" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from snapshot" -a 'get'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from auth limits metadata metadata-types shape snapshot sobject users" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from access-token jwt sfdx-url web" -a 'login'
complete -c sf -n "__fish_seen_subcommand_from org" -a 'logout'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from agent authoring-bundle" -a 'open'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from sandbox" -a 'refresh'
complete -c sf -n "__fish_seen_subcommand_from org; and not __fish_seen_subcommand_from sandbox scratch" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from package" -a 'convert'
complete -c sf -n "__fish_seen_subcommand_from package" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from package" -a 'delete'
complete -c sf -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from report" -a 'install'
complete -c sf -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from list" -a 'installed'
complete -c sf -n "__fish_seen_subcommand_from package" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from abort list report schedule" -a 'push-upgrade'
complete -c sf -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from report" -a 'uninstall'
complete -c sf -n "__fish_seen_subcommand_from package" -a 'update'
complete -c sf -n "__fish_seen_subcommand_from package; and not __fish_seen_subcommand_from create delete displayancestry displaydependencies list promote report retrieve update" -a 'version'
complete -c sf -n "__fish_seen_subcommand_from package1; and not __fish_seen_subcommand_from create display list" -a 'version'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'add'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'discover'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'inspect'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'install'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'link'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'remove'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'reset'
complete -c sf -n "__fish_seen_subcommand_from plugins; and not __fish_seen_subcommand_from verify" -a 'trust'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'uninstall'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'unlink'
complete -c sf -n "__fish_seen_subcommand_from plugins" -a 'update'
complete -c sf -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from mdapi source source-behavior" -a 'convert'
complete -c sf -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from source tracking" -a 'delete'
complete -c sf -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from cancel pipeline preview quick report resume start validate" -a 'deploy'
complete -c sf -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from manifest" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from ignored" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from tracking" -a 'reset'
complete -c sf -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from preview start" -a 'retrieve'
complete -c sf -n "__fish_seen_subcommand_from schema; and not __fish_seen_subcommand_from field platformevent sobject tab" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from sobject" -a 'describe'
complete -c sf -n "__fish_seen_subcommand_from sobject" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from static-resource" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from visualforce; and not __fish_seen_subcommand_from component page" -a 'generate'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from generate" -a 'agent-spec'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from generate" -a 'authoring-bundle'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from generate" -a 'template'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from generate" -a 'test-spec'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from publish" -a 'authoring-bundle'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from test" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from test" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from test" -a 'results'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from test" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from test" -a 'run'
complete -c sf -n "__fish_seen_subcommand_from agent and __fish_seen_subcommand_from validate" -a 'authoring-bundle'
complete -c sf -n "__fish_seen_subcommand_from analytics and __fish_seen_subcommand_from generate" -a 'template'
complete -c sf -n "__fish_seen_subcommand_from apex and __fish_seen_subcommand_from generate" -a 'class'
complete -c sf -n "__fish_seen_subcommand_from apex and __fish_seen_subcommand_from generate" -a 'trigger'
complete -c sf -n "__fish_seen_subcommand_from apex and __fish_seen_subcommand_from get" -a 'log'
complete -c sf -n "__fish_seen_subcommand_from apex and __fish_seen_subcommand_from get" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from apex and __fish_seen_subcommand_from list" -a 'log'
complete -c sf -n "__fish_seen_subcommand_from apex and __fish_seen_subcommand_from run" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from apex and __fish_seen_subcommand_from tail" -a 'log'
complete -c sf -n "__fish_seen_subcommand_from api and __fish_seen_subcommand_from request" -a 'graphql'
complete -c sf -n "__fish_seen_subcommand_from api and __fish_seen_subcommand_from request" -a 'rest'
complete -c sf -n "__fish_seen_subcommand_from cmdt and __fish_seen_subcommand_from generate" -a 'field'
complete -c sf -n "__fish_seen_subcommand_from cmdt and __fish_seen_subcommand_from generate" -a 'fromorg'
complete -c sf -n "__fish_seen_subcommand_from cmdt and __fish_seen_subcommand_from generate" -a 'object'
complete -c sf -n "__fish_seen_subcommand_from cmdt and __fish_seen_subcommand_from generate" -a 'record'
complete -c sf -n "__fish_seen_subcommand_from cmdt and __fish_seen_subcommand_from generate" -a 'records'
complete -c sf -n "__fish_seen_subcommand_from community and __fish_seen_subcommand_from list" -a 'template'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from bulk" -a 'results'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from create" -a 'file'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from create" -a 'record'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from delete" -a 'bulk'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from delete" -a 'record'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from delete" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from export" -a 'bulk'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from export" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from export" -a 'tree'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from get" -a 'record'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from import" -a 'bulk'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from import" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from import" -a 'tree'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from update" -a 'bulk'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from update" -a 'record'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from update" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from upsert" -a 'bulk'
complete -c sf -n "__fish_seen_subcommand_from data and __fish_seen_subcommand_from upsert" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from dev and __fish_seen_subcommand_from audit" -a 'messages'
complete -c sf -n "__fish_seen_subcommand_from dev and __fish_seen_subcommand_from convert" -a 'messages'
complete -c sf -n "__fish_seen_subcommand_from dev and __fish_seen_subcommand_from convert" -a 'script'
complete -c sf -n "__fish_seen_subcommand_from dev and __fish_seen_subcommand_from generate" -a 'command'
complete -c sf -n "__fish_seen_subcommand_from dev and __fish_seen_subcommand_from generate" -a 'flag'
complete -c sf -n "__fish_seen_subcommand_from dev and __fish_seen_subcommand_from generate" -a 'plugin'
complete -c sf -n "__fish_seen_subcommand_from flow and __fish_seen_subcommand_from get" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from flow and __fish_seen_subcommand_from run" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from data; and not __fish_seen_subcommand_from delete status upsert" -a 'bulk'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from lightning; and not __fish_seen_subcommand_from test" -a 'lwc'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from package; and not __fish_seen_subcommand_from list" -a 'push-upgrade'
complete -c sf -n "__fish_seen_subcommand_from info and __fish_seen_subcommand_from releasenotes" -a 'display'
complete -c sf -n "__fish_seen_subcommand_from lightning and __fish_seen_subcommand_from generate" -a 'app'
complete -c sf -n "__fish_seen_subcommand_from lightning and __fish_seen_subcommand_from generate" -a 'component'
complete -c sf -n "__fish_seen_subcommand_from lightning and __fish_seen_subcommand_from generate" -a 'event'
complete -c sf -n "__fish_seen_subcommand_from lightning and __fish_seen_subcommand_from generate" -a 'interface'
complete -c sf -n "__fish_seen_subcommand_from lightning and __fish_seen_subcommand_from generate" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from logic and __fish_seen_subcommand_from get" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from logic and __fish_seen_subcommand_from run" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from assign" -a 'permset'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from assign" -a 'permsetlicense'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from create" -a 'sandbox'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from create" -a 'scratch'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from create" -a 'shape'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from create" -a 'snapshot'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from create" -a 'user'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from delete" -a 'sandbox'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from delete" -a 'scratch'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from delete" -a 'shape'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from delete" -a 'snapshot'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from disable" -a 'tracking'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from display" -a 'user'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from enable" -a 'tracking'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from generate" -a 'password'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from get" -a 'snapshot'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list" -a 'auth'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list" -a 'limits'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list" -a 'metadata'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list" -a 'metadata-types'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list" -a 'shape'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list" -a 'snapshot'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from record-counts" -a 'sobject'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list" -a 'users'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from login" -a 'access-token'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from login" -a 'jwt'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from login" -a 'sfdx-url'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from login" -a 'web'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from open" -a 'agent'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from open" -a 'authoring-bundle'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from refresh" -a 'sandbox'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from resume" -a 'sandbox'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from resume" -a 'scratch'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from install" -a 'report'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from installed" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from push-upgrade" -a 'abort'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from push-upgrade" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from push-upgrade" -a 'report'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from push-upgrade" -a 'schedule'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from uninstall" -a 'report'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from list report" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'delete'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'displayancestry'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'displaydependencies'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'promote'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'report'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'retrieve'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version" -a 'update'
complete -c sf -n "__fish_seen_subcommand_from package1 and __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from get" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from package1 and __fish_seen_subcommand_from version" -a 'display'
complete -c sf -n "__fish_seen_subcommand_from package1 and __fish_seen_subcommand_from version" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from plugins and __fish_seen_subcommand_from trust" -a 'verify'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from convert" -a 'mdapi'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from convert" -a 'source'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from convert" -a 'source-behavior'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from delete" -a 'source'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from delete" -a 'tracking'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy" -a 'cancel'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from quick report resume start validate" -a 'pipeline'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy" -a 'preview'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy" -a 'quick'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy" -a 'report'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy" -a 'start'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy" -a 'validate'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from generate" -a 'manifest'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from list" -a 'ignored'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from reset" -a 'tracking'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from retrieve" -a 'preview'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from retrieve" -a 'start'
complete -c sf -n "__fish_seen_subcommand_from schema and __fish_seen_subcommand_from generate" -a 'field'
complete -c sf -n "__fish_seen_subcommand_from schema and __fish_seen_subcommand_from generate" -a 'platformevent'
complete -c sf -n "__fish_seen_subcommand_from schema and __fish_seen_subcommand_from generate" -a 'sobject'
complete -c sf -n "__fish_seen_subcommand_from schema and __fish_seen_subcommand_from generate" -a 'tab'
complete -c sf -n "__fish_seen_subcommand_from visualforce and __fish_seen_subcommand_from generate" -a 'component'
complete -c sf -n "__fish_seen_subcommand_from visualforce and __fish_seen_subcommand_from generate" -a 'page'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from data and __fish_seen_subcommand_from bulk" -a 'delete'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from data and __fish_seen_subcommand_from bulk" -a 'status'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from data and __fish_seen_subcommand_from bulk" -a 'upsert'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from lightning and __fish_seen_subcommand_from lwc; and not __fish_seen_subcommand_from create run setup" -a 'test'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from package and __fish_seen_subcommand_from push-upgrade" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from org and __fish_seen_subcommand_from list and __fish_seen_subcommand_from sobject" -a 'record-counts'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version and __fish_seen_subcommand_from create" -a 'list'
complete -c sf -n "__fish_seen_subcommand_from package and __fish_seen_subcommand_from version and __fish_seen_subcommand_from create" -a 'report'
complete -c sf -n "__fish_seen_subcommand_from package1 and __fish_seen_subcommand_from version and __fish_seen_subcommand_from create" -a 'get'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy and __fish_seen_subcommand_from pipeline" -a 'quick'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy and __fish_seen_subcommand_from pipeline" -a 'report'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy and __fish_seen_subcommand_from pipeline" -a 'resume'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy and __fish_seen_subcommand_from pipeline" -a 'start'
complete -c sf -n "__fish_seen_subcommand_from project and __fish_seen_subcommand_from deploy and __fish_seen_subcommand_from pipeline" -a 'validate'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from lightning and __fish_seen_subcommand_from lwc and __fish_seen_subcommand_from test" -a 'create'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from lightning and __fish_seen_subcommand_from lwc and __fish_seen_subcommand_from test" -a 'run'
complete -c sf -n "__fish_seen_subcommand_from force and __fish_seen_subcommand_from lightning and __fish_seen_subcommand_from lwc and __fish_seen_subcommand_from test" -a 'setup'
