# See: /usr/share/doc/mpd/mpdconf.example

#Files and directories
music_directory "/home/markm/Music/"
playlist_directory "/home/markm/.mpd/playlists/"
pid_file "/home/markm/.mpd/pid"
state_file "/home/markm/.mpd/mpdstate"
log_file "/home/markm/.mpd/log"
sticker_file "/home/markm/.mpd/sticker.sql"

user "markm"

bind_to_address "/home/markm/.mpd/socket"
log_level "notice"
metadata_to_use "artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update "yes"
auto_update_depth "3"

follow_outside_symlinks "yes"
follow_inside_symlinks "yes"

audio_output {
    type        "pipewire"
    name        "PipeWire"
}

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}

decoder {
    plugin "wildmidi"
    enabled "no"
}
