# vim: set ft=dosini :
# More options: https://github.com/DreamMaoMao/mango/wiki/

source=./exec.conf
source=./effects.conf
source=./animations.conf
source=./layouts.conf
source=./misc.conf
source=./input.conf
source=./appearance.conf
source=./tagrules.conf
source=./layerrules.conf

source=./dms/colors.conf
source=./dms/outputs.conf
source=./dms/binds.conf
source=./dms/cursor.conf
source=./dms/layout.conf
source=./dms/windowrules.conf
