[colors.primary]
background = '#0e1513'
foreground = '#dde4e1'

[colors.selection]
text = '#dde4e1'
background = '#005047'

[colors.cursor]
text = '#0e1513'
cursor = '#83d5c6'

[colors.normal]
black   = '#0e1513'
red     = '#f49b6e'
green   = '#6ad571'
yellow  = '#fff372'
blue    = '#6ccab9'
magenta = '#1c6255'
cyan    = '#83d5c6'
white   = '#d2dfdd'

[colors.bright]
black   = '#808a88'
red     = '#ffbf9f'
green   = '#a5ffab'
yellow  = '#fff7a5'
blue    = '#9deadc'
magenta = '#bafff2'
cyan    = '#d2fff6'
white   = '#f8fffd'
