# : Manager [[[

[mgr]
cwd = { fg = "#dde4e1" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#65b5ff", bg = "#65b5ff" }
marker_cut      = { fg = "#cbe6ff", bg = "#cbe6ff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#accae5", bg = "#accae5" }

# Count
count_copied   = { fg = "#001e30", bg = "#cbe6ff" }
count_cut      = { fg = "#001e30", bg = "#cbe6ff" }
count_selected = { fg = "#003730", bg = "#accae5" }

# Border
border_symbol = "│"
border_style  = { fg = "#83d5c6" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#83d5c6", bold = true, bg = "#0e1513" }
inactive  = { fg = "#b1ccc6", bg = "#0e1513" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#83d5c6", fg = "#003730", bold = true }
normal_alt  = { bg = "#3f4946", fg = "#bec9c5" }

# Select mode
select_main = { bg = "#b1ccc6", fg = "#1c3530", bold = true }
select_alt  = { bg = "#3f4946", fg = "#bec9c5" }

# Unset mode
unset_main = { bg = "#accae5", fg = "#143349", bold = true }
unset_alt  = { bg = "#3f4946", fg = "#bec9c5" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#5a8a7f" }
perm_write = { fg = "#3b7fbd" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#329cff" }
perm_sep   = { fg = "#1edab6" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#83d5c6", bg = "#343b39" }
progress_error  = { fg = "#ffb4ab", bg = "#343b39" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343b39" }
cand = { fg = "#83d5c6" }
rest = { fg = "#003730" }
desc = { fg = "#dde4e1" }
separator = " ▶ "
separator_style = { fg = "#dde4e1" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#accae5" }
title_warn  = { fg = "#83d5c6" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#83d5c6" }
active = { fg = "#accae5", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#83d5c6" }
value  = { fg = "#dde4e1" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#83d5c6", bg = "#003730" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#83d5c6" }
title   = {}
hovered = { fg = "#cbe6ff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#dde4e1" }
run    = { fg = "#dde4e1" }
footer = { fg = "#1c3530", bg = "#b1ccc6" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dde4e1" },
    { url = "*/", fg = "#83d5c6" },
]

# : ]]]
