# Hyprland Configuration
# https://wiki.hypr.land/Configuring/

# ==================
# MISC
# ==================
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

xwayland {
  force_zero_scaling = true
  use_nearest_neighbor = true
  enabled = true
}

# ==================
# STARTUP APPS
# ==================
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP && systemctl --user start hyprland-session.target
exec-once = hyprpm reload
#exec-once = swww-daemon & sleep 0.1 & swww img $HOME/Pictures/DankWallpapers/dms_wallpaper_current.png
#exec-shutdown = hyprctl keyword monitor DP-2,3840x2160@165,0x0,1.0,vrr,1


# ==================
# INPUT CONFIG
# ==================
input {
    kb_layout = us
    numlock_by_default = true
    follow_mouse = 0
}

cursor {
    no_warps = true
}

# ==================
# GENERAL LAYOUT
# ==================
general {
    layout = dwindle
}

dwindle {
   force_split = 2
   # split_width_multiplier = .8
}

master {
    orientation = left
    mfact = 0.50
    slave_count_for_center_master = 0
    always_keep_position = true
    center_master_fallback = left
}

scrolling{
    fullscreen_on_one_column = true
    column_width = 0.5
    focus_fit_method = 1
    follow_focus = true
    follow_min_visible = 1.0
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0
    direction = right
}

source = ./dms/colors.conf
source = ./dms/outputs.conf
source = ./dms/decorations.conf
source = ./dms/animations.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
source = ./dms/binds.conf
source = ./dms/windowrules.conf
